const nonProfitsPosts = [
  {
    id: "1",
    img: "/img/eksempelbilde1.png",
    name: "Redd barna",
    averageDonated: 300,
    aboutText: "lorem ipsum cadeva ivo fiva pova ipsum",
    categories: ["humanitarian", "recommended"],
  },
  {
    id: "2",
    img: "/img/eksempelbilde2.png",
    name: "Charity:Water",
    averageDonated: 200,
    aboutText: "lorem ipsum cadeva ivo fiva pova lorem ",
    categories: ["environment", "recommended"],
  },
  {
    id: "3",
    img: "/img/eksempelbilde10.png",
    name: "Leger uten grenser",
    averageDonated: 150,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["humanitarian", ""],
  },
  {
    id: "4",
    img: "/img/eksempelbilde4.png",
    name: "Occean Conservacy",
    averageDonated: 300,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["environment", "recommended"],
  },
  {
    id: "5",
    img: "/img/eksempelbilde5.png",
    name: "Amnesty",
    averageDonated: 350,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["equality", ""],
  },
  {
    id: "6",
    img: "/img/eksempelbilde6.png",
    name: "Education Trust",
    averageDonated: 400,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["education", "recommended"],
  },
  {
    id: "7",
    img: "/img/eksempelbilde7.png",
    name: "The tomorrow school",
    averageDonated: 200,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["education", ""],
  },
  {
    id: "8",
    img: "/img/eksempelbilde8.png",
    name: "Care Norge",
    averageDonated: 300,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["humanitarian", "recommended"],
  },
  {
    id: "9",
    img: "/img/eksempelbilde9.png",
    name: "Forum 18",
    averageDonated: 200,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["environment", ""],
  },
  {
    id: "10",
    img: "/img/eksempelbilde11.png",
    name: "African Education Foundation",
    averageDonated: 300,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["education", ""],
  },
  {
    id: "11",
    img: "/img/eksempelbilde12.png",
    name: "Earth Justice",
    averageDonated: 200,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["equality", ""],
  },
  {
    id: "12",
    img: "/img/eksempelbilde13.png",
    name: "United way",
    averageDonated: 300,
    aboutText: "lorem ipsum cadeva ivo fiva pova",
    categories: ["equality", "recommended"],
  },
];

export default nonProfitsPosts;
